"""add platform fields to vacancies

Revision ID: 9efc1f1a783a
Revises: 6cfd28cda862
Create Date: 2026-04-21 23:08:34.401280

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9efc1f1a783a'
down_revision: Union[str, None] = '6cfd28cda862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('platform', sa.String(), nullable=False, server_default='hh'))
    op.add_column('vacancies', sa.Column('integration_mode', sa.String(), nullable=False, server_default='official_api'))
    op.add_column('vacancies', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_vacancies_external_id'), 'vacancies', ['external_id'], unique=False)
    op.alter_column('vacancies', 'platform', server_default=None)
    op.alter_column('vacancies', 'integration_mode', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_external_id'), table_name='vacancies')
    op.drop_column('vacancies', 'external_id')
    op.drop_column('vacancies', 'integration_mode')
    op.drop_column('vacancies', 'platform')
    # ### end Alembic commands ###
